### ISSUE TITLE
can't test 

### ISSUE THREAD

**Issue by AhmedWahdanZ** [cah4a/dart_nock#1]
`[+1496 ms] 
           Compiler message:
[   +2 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/nock-1.0.1/lib/src/http_headers.dart:53:8: Error: The method 'MockHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
[        ]   void add(String name, value) {
[        ]        ^
[        ] org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:695:8: Context: This is the overridden method ('add').
[        ]   void add(String name, Object value,
[        ]        ^
[   +1 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/nock-1.0.1/lib/src/http_headers.dart:69:3: Error: The method 'MockHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
[        ]   set(String name, Object value) {
[        ]   ^
[        ] org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:704:8: Context: This is the overridden method ('set').
[        ]   void set(String name, Object value,
[        ]        ^
`

**Comment by cah4a** [comment]
Could you please provide more information about dart version?

**Comment by cah4a** [comment]
I guess you are using dart from the beta channel. There are changes in the signatures of HttpHeaders.add() and HttpHeaders.set() methods.

I've updated the package, try to upgrade to version 1.0.2.
