### ISSUE TITLE
Question: is it possible to not mock certain URLs?

### ISSUE THREAD

**Issue by jseminck** [cah4a/dart_nock#10]
Hello, first of all apologies as this is not necessarily an issue but more of a question that I could not figure out from the docs or API reference. Is it possible to mock only certain URLs and not others?

For example, mock `http://localhost:8080` urls, but do not mock URLs to `https://flagcdn.com/` or some similar CDN?

Thanks

**Comment by cah4a** [comment]
Hey, @jseminck

No, currently nock doesn't support performing real HTTP requests. Any request that didn't mock will fail the test using `NetConnectionNotAllowed` error.

I don't know whether it is a good idea, cuz in this case the tests will test much more than the code: internet connection, DNS, SSL, remote servers, response content, etc...

Reproducibility is a central tenet of testing. So I'm trying to avoid testing a real API that belongs to me and, of course, don't want to test some API that doesn't.

**Comment by jseminck** [comment]
I agree with you, and I managed to find another workaround to my problem. 

Just for context, we are using https://pub.dev/packages/cached_network_image to get flags from https://flagcdn.com/ and this package throws exceptions in case an invalid URL is given to it. I didn't want to mock out all the flags as that seems kind of silly. My other best solution was to create a wrapper widget around `CachedNetworkImage` that returns a `SizedBox()` when running the test.

Thanks for the reply!

**Comment by cah4a** [comment]
Yeah, I bet this is the best solution.

Thanks for sharing your experience. It could be useful for others who face similar issues.
