### ISSUE TITLE
matching uri with path-params

### ISSUE THREAD

**Issue by rulila52** [cah4a/dart_nock#11]
We can use query, in which, using params, we can perform the necessary actions.

```
interceptor = nock(baseurl).get(dynamicPath)
        ..query((params) => true)...
```

But what if I need to check it by path params (https://myUrl/myParam )? Is it possible to access the intercepted url?

**Comment by cah4a** [comment]
Hey @rulila52,

Library supports matchers for url path: `nock(baseUrl).get(startsWith('/myUrl/'))`.

Is that work for you?
