### ISSUE TITLE
Using Nock outside of tests?

### ISSUE THREAD

**Issue by StankoLitebit** [cah4a/dart_nock#17]
Hello. Firstly, thanks for Nock, really makes mocking smooth.

I am curious if it is possible to set up Nock and run it when app is ran with a certain 'Mock' flavor? 

The plan was to look somehow like this:

```
Future setupMock(String baseUrl) async {
  final scope = nock(baseUrl);
  scope.get('/portfolio').reply(200, getPortfolio);
  scope.post('/portfolio').reply(201, getPortfolio);
  scope.get('/payment-methods').reply(200, getPaymentMethods);
```

However, when I try running / debugging the app, I get the following error:

```
Error: Couldn't resolve the package 'nock' in 'package:nock/nock.dart'.
: Error: Not found: 'package:nock/nock.dart'
../…/mock/setup_mock.dart:21
import 'package:nock/nock.dart';
       ^
```

Is it able to run Nock, or is it by design only intended for tests?

**Comment by cah4a** [comment]
Hello,
It's a great pleasure to hear that you like nock.

We didn't do anything intentionally to prevent running nock on a device.
However, we didn't check whether the thing even work in that case. 😅

For me, it looks like the compiler omits test dependencies.
You could try to add `test` and `nock` packages as regular dependencies of your app. 
Maybe that will work.

If it doesn't, you could use your version for HttpOverrides:
```dart
class YourAppOverrides extends HttpOverrides {
  static void init() {
    HttpOverrides.global = YourAppOverrides();
  }

  @override
  HttpClient createHttpClient(SecurityContext? context) {
    // @todo: implement me
  }
}
```

Out of curiosity, what issue are you trying to solve?
