### ISSUE TITLE
Response body mocking

### ISSUE THREAD

**Issue by dricholm** [cah4a/dart_nock#2]
First of all, thank you for the package, it works great!

I have two questions/improvement ideas regarding mocked responses.

Currently the `replay()` function has body as required parameter. However the response body is not required in some cases: a 204 response or even with 201 etc. Could this be changed to an optional parameter? For now I provide null as the body and it seems to work okay.

Another question is also regarding the `replay()` function. The original nock has the name as `reply()` as in replying to a request I guess. I think replay sounds a bit weird here. How come this was changed?

**Comment by cah4a** [comment]
Hi @dricholm!

About `reply` name, I agree, my bad :) I will add a new method and deprecate `replay` method.

The main issue about `body` as an optional parameter is that dart couldn't mix positional and named arguments. And in most cases, there is a body.

What do you think the signature might look like?

**Comment by dricholm** [comment]
Thanks for the quick reply @cah4a!

I see, deprecating the old and adding a new one sounds good.

About the `body` parameter you have a point, I haven't thought about that. I had a look at the `Response` class in `http`, it also uses `String body, int statusCode` as positional and others such as `headers` as named parameters. The only idea I have is making the `body` also named, but since a response with body is used most of the time it is more convenient to leave it as it is now.

**Comment by cah4a** [comment]
Hey @dricholm!

I've just published v1.1.0 that contains the typo fix.
Sorry for the delay and thanks again for the contribution.
