### ISSUE TITLE
Error: The non-abstract class '_Cookie' is missing implementations for these members:  Cookie.sameSite

### ISSUE THREAD

**Issue by Gursewak-Uppal** [cah4a/dart_nock#23]
HI, I recently upgraded my flutter version and all of its dependencies - including nock from 1.2.1 to 1.2.2 (latest version).

Since that upgrade I get the following errors while running tests with nock@1.2.2

<img width="1375" alt="image" src="https://github.com/cah4a/dart_nock/assets/28809960/79b3360e-aa7c-4578-97e7-24425511fb72">

**Comment by cah4a** [comment]
Published new version. See #22

**Comment by cah4a** [comment]
If it's not working, please reopen the issue.
