### ISSUE TITLE
Multiple requests

### ISSUE THREAD

**Issue by pblinux** [cah4a/dart_nock#5]
Hi again @cah4a 

I'm having troubles with mocking multiple requests. I have an Api class that performs a couple of requests but always is needed to be called the `first()` method before the others because depends on the result.

The first request is called but the second is throwing a `NetConnectionNotAllowed` with pending mocks. Here's the example I'm trying to run:
https://gist.github.com/pblinux/54a05e3b9afeac1cd37893550236f44f

Maybe I'm using nock in a wrong way?

**Comment by cah4a** [comment]
Hi!

Sorry for the late reply.

Seems passing strings instead of matchers is working as expected.
I mean `DioError [DioErrorType.RESPONSE]: Http status error [404]` is arising.

I was rushing forward while implementing URL matching, maybe should do some fixes to match the expected behavior.

Thanks for the issue. That helps a lot.

**Comment by cah4a** [comment]
Hey @pblinux!

I've updated the package recently to support that use case. Just use version 1.1.2.
Thanks for your contribution!

**Comment by jerem17** [comment]
Hello,
first of all thank you for the great work!
On the other hand, I have the same problem, I do 2 nock (url) .get ("/ example1) and another nock (url) .get (" / example2). The first goes well, but the second timeout ... I put "persist" to try but that doesn't change anything ...
```
 nock("https://example.com/1").get("")
        ..reply(
          200,
          "ahaha",
        );

   nock("https://example.com/2").get("")
        ..reply(
          200,
          "ohoho",
        );
```

**Comment by cah4a** [comment]
Hey @jerem17,

Thanks for the kind words!

Just tried sequential scenario and it seems working:

```dart
import 'package:test/test.dart';
import 'package:nock/nock.dart';
import 'package:http/http.dart' as http;

void main() {
  setUpAll(() {
    nock.init();
    nock.defaultBase = "http://example.com";
  });

  setUp(() {
    nock.cleanAll();
  });

  test('sequntal_requests', () async {
    final interceptor = nock.get("/users")
      ..reply(
        200,
        "result1",
      );

    final interceptor2 = nock.get("/users")
      ..reply(
        200,
        "result2",
      );

    final request1 = await http.get("http://example.com/users");
    final request2 = await http.get("http://example.com/users");

    expect(request1.body, "result1");
    expect(request2.body, "result2");

    expect(interceptor.isDone, true);
    expect(interceptor2.isDone, true);
  });
```

```yaml
name: sequential_scenario_dart_nock_test

dev_dependencies:
  test: ^1.15.7
  nock: ^1.1.2
```

```
$ dart --version
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
```

If that doesn't help feel free to open a new issue, with more detailed information.

**Comment by jerem17** [comment]
Thank you for your quick feedback! This changes nothing, I think the problem is that I am calling an external function. It looks like this:

my test.dart : 

```
 test('test1', () async {
    
      final interceptor = nock.get("/users1")
        ..reply(
          200,
          "result1",
        );

      final interceptor2 = nock.get("/users2")
        ..reply(
          200,
          "result2",
        );


      expect(() async => auth.signIn("us1", "us2"), throwsException);
    }, timeout: Timeout(Duration(seconds: 10)));
```


my external function, which is in a class I called "Auth" and which uses the "requests" package for http requests;


```
class Auth {
signIn(String us1, String us2) {
 await Requests.get("http://example.com/users1", headers: {});
    print("step 1");

    await Requests.get("http://example.com/users2", headers: {});
    print("step 2" );
    }
}
```

The first request is to intercept, but not the second: /

**Comment by cah4a** [comment]
Should your code throw an exception?

```dart
import 'package:test/test.dart';
import 'package:nock/nock.dart';
import 'package:http/http.dart' as http;

Future<void> extern_function() async {
    await http.get("http://example.com/users1");
    await http.get("http://example.com/users2");
}

void main() {
  setUpAll(() {
    nock.init();
    nock.defaultBase = "http://example.com";
  });

  setUp(() {
    nock.cleanAll();
  });

  test('sequntal_requests', () async {
    nock.get("/users1")
      ..reply(
        200,
        "result1",
      );

    nock.get("/users2")
      ..reply(
        200,
        "result2",
      );
      
    // TEST NOT PASS:
    // expect(() async => extern_function(), throwsException);
      
    // TEST PASS:
    expect(extern_function(), completes);
  });
}
```

**Comment by jerem17** [comment]
So I got some good news for you and some bad news for me lol

When I test your code using the http package, it works perfectly, however, when I use the requests package, it doesn't work anymore.

func : 

```
Future<void> extern_function() async {
  print("1");
  await Requests.get("http://example.com/users1");
  print("2");
  await Requests.get("http://example.com/users2");
  print("3");
}
```


result :
```
1
2
TimeoutException after 0:00:10.000000: Test timed out after 10 seconds.
dart:isolate  _RawReceivePortImpl._handleMessage
```


 So I guess I have to look at the "request" package side to find the solution to my problem

**Comment by cah4a** [comment]
Hmm, that's pretty interesting.
Not that good news, btw. Nock has to support any library out there.

**Comment by jerem17** [comment]
in addition I use the requests package in all my application lol
rip

Anyway thank you very much for taking the time to answer me and help me

**Comment by cah4a** [comment]
Hey @jerem17, I've got a solution for you.

Try adding `TestWidgetsFlutterBinding.ensureInitialized();` in setUpAll hook function.

Cookies won't work anyway, because it saved to SharedPreferences which doesn't exist at test time.
If you rely on them, you might [open an issue there](https://github.com/jossef/requests/issues).

**Comment by jerem17** [comment]
You are a genius! Thank you very much, it works now.

**Comment by cah4a** [comment]
@jerem17
My pleasure!
