### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by pblinux** [cah4a/dart_nock#7]
Hi @cah4a! hope you are doing well.

I was wondering if the package will get null safety support? I have a package that depends on nock but I have not yet been able to migrate it.

:smile:

**Comment by cah4a** [comment]
Hey @pblinux!

Yesterday I've published v1.2.0. With null-safety support.
But it doesn't have a "null-safe" badge, because of `test` package dependency, which still doesn't have full null-safety support in stable releases.

**Comment by pblinux** [comment]
Sorry I didn't respond. Thank you very much @cah4a for include null safety support, your package is so useful. 👏 🙏

**Comment by cah4a** [comment]
@pblinux 
My pleasure!

**Comment by cah4a** [comment]
Now [nock](https://pub.dev/packages/nock) has the badge.
I'm closing the issue.

Thanks again for the collaboration!
